name =input("请输入你的名字")
age = input("请输入你的年龄")
height = input("请输入你的身高")
weight = input("请输入你的体重")
birthday = input("请输入你的生日")
money = input("请输入你的薪水")
tel = input("请输入你的电话")
print("姓名是%s"%name)
print("年龄是%s"%age)
print("身高是%s"%height)
print("体重是%s"%weight)
print("生日是%s"%birthday)
print("薪水是%s"%money)
print("电话是%s"%tel)
